import { FullMovie } from './autotypes'

export type IKinopoiskDevParams = Partial<Record<keyof IKinopoiskDevParamsValues, string | number>>

export type IKinopoiskDevSearchParams = Partial<Record<QueryValuesUnion, string>>

type QueryValuesUnion =
	| 'selectFields'
	| 'sortField'
	| 'sortType'
	| 'page'
	| 'limit'
	| 'id'
	| 'externalId.kpHD'
	| 'externalId.imdb'
	| 'externalId.tmdb'
	| 'name'
	| 'alternativeName'
	| 'enName'
	| 'names.name'
	| 'type'
	| 'typeNumber'
	| 'year'
	| 'description'
	| 'shortDescription'
	| 'slogan'
	| 'status'
	| 'rating.kp'
	| 'rating.imdb'
	| 'rating.tmdb'
	| 'rating.filmCritics'
	| 'rating.russianFilmCritics'
	| 'rating.await'
	| 'votes.kp'
	| 'votes.imdb'
	| 'votes.tmdb'
	| 'votes.filmCritics'
	| 'votes.russianFilmCritics'
	| 'votes.await'
	| 'movieLength'
	| 'ratingMpaa'
	| 'ageRating'
	| 'logo.url'
	| 'poster.url'
	| 'poster.previewUrl'
	| 'backdrop.url'
	| 'backdrop.previewUrl'
	| 'videos.trailers.url'
	| 'videos.trailers.name'
	| 'videos.trailers.site'
	| 'videos.trailers.type'
	| 'genres,name'
	| 'countries.name'
	| 'persons.id'
	| 'persons.photo'
	| 'persons.name'
	| 'persons.enName'
	| 'reviewInfo.count'
	| 'reviewInfo.positiveCount'
	| 'reviewInfo.percentage'
	| 'seasonsInfo.number'
	| 'seasonsInfo.episodesCount'
	| 'budget.value'
	| 'budget.currency'
	| 'fees.world.value'
	| 'fees.world.currency'
	| 'fees.russia.value'
	| 'fees.russia.currency'
	| 'fees.usa.value'
	| 'fees.usa.currency'
	| 'premiere.country'
	| 'premiere.world'
	| 'premiere.russia'
	| 'premiere.digital'
	| 'premiere.cinema'
	| 'similarMovies.id'
	| 'sequelsAndPrequels.id'
	| 'watchability.items.name'
	| 'releaseYears.start'
	| 'releaseYears.end'
	| 'top10'
	| 'top250'
	| 'ticketsOnSale'
	| 'totalSeriesLength'
	| 'seriesLength'
	| 'isSeries'
	| 'audience.count'
	| 'audience.country'

export interface IKinopoiskDevParamsValues {
	// selectFields?: keyof FullMovie[]
	selectFields?: QueryValuesUnion
	sortField?: QueryValuesUnion
	sortType?: QueryValuesUnion
	page?: QueryValuesUnion
	limit?: QueryValuesUnion
	id?: QueryValuesUnion
	externalIdKpHD?: QueryValuesUnion
	externalIdImdb?: QueryValuesUnion
	externalIdTmdb?: QueryValuesUnion
	name?: QueryValuesUnion
	alternativeName?: QueryValuesUnion
	enName?: QueryValuesUnion
	namesName?: QueryValuesUnion
	type?: QueryValuesUnion
	typeNumber?: QueryValuesUnion
	year?: QueryValuesUnion
	description?: QueryValuesUnion
	shortDescription?: QueryValuesUnion
	slogan?: QueryValuesUnion
	status?: QueryValuesUnion
	ratingKp?: QueryValuesUnion
	ratingImdb?: QueryValuesUnion
	ratingTmdb?: QueryValuesUnion
	ratingFilmCritics?: QueryValuesUnion
	ratingRussianFilmCritics?: QueryValuesUnion
	ratingAwait?: QueryValuesUnion
	votesKp?: QueryValuesUnion
	votesImdb?: QueryValuesUnion
	votesTmdb?: QueryValuesUnion
	votesFilmCritics?: QueryValuesUnion
	votesRussianFilmCritics?: QueryValuesUnion
	votesAwait?: QueryValuesUnion
	movieLength?: QueryValuesUnion
	ratingMpaa?: QueryValuesUnion
	ageRating?: QueryValuesUnion
	logoUrl?: QueryValuesUnion
	posterUrl?: QueryValuesUnion
	posterPreviewUrl?: QueryValuesUnion
	backdropUrl?: QueryValuesUnion
	backdropPreviewUrl?: QueryValuesUnion
	videosTrailersUrl?: QueryValuesUnion
	videosTrailersName?: QueryValuesUnion
	videosTrailersSite?: QueryValuesUnion
	videosTrailersType?: QueryValuesUnion
	genresName?: QueryValuesUnion
	countriesName?: QueryValuesUnion
	personsId?: QueryValuesUnion
	personsPhoto?: QueryValuesUnion
	personsName?: QueryValuesUnion
	personsEnName?: QueryValuesUnion
	reviewInfoCount?: QueryValuesUnion
	reviewInfoPositiveCount?: QueryValuesUnion
	reviewInfoPercentage?: QueryValuesUnion
	seasonsInfoNumber?: QueryValuesUnion
	seasonsInfoEpisodesCount?: QueryValuesUnion
	budgetValue?: QueryValuesUnion
	budgetCurrency?: QueryValuesUnion
	feesWorldValue?: QueryValuesUnion
	feesWorldCurrency?: QueryValuesUnion
	feesRussiaValue?: QueryValuesUnion
	feesRussiaCurrency?: QueryValuesUnion
	feesUsaValue?: QueryValuesUnion
	feesUsaCurrency?: QueryValuesUnion
	premiereCountry?: QueryValuesUnion
	premiereWorld?: QueryValuesUnion
	premiereRussia?: QueryValuesUnion
	premiereDigital?: QueryValuesUnion
	premiereCinema?: QueryValuesUnion
	similarMoviesId?: QueryValuesUnion
	sequelsAndPrequelsId?: QueryValuesUnion
	watchabilityItemsName?: QueryValuesUnion
	releaseYearsStart?: QueryValuesUnion
	releaseYearsEnd?: QueryValuesUnion
	top10?: QueryValuesUnion
	top250?: QueryValuesUnion
	ticketsOnSale?: QueryValuesUnion
	totalSeriesLength?: QueryValuesUnion
	seriesLength?: QueryValuesUnion
	isSeries?: QueryValuesUnion
	audienceCount?: QueryValuesUnion
	audienceCountry?: QueryValuesUnion
}

export const KinopoiskDevParamsValues: IKinopoiskDevParamsValues = {
	selectFields: 'selectFields',
	sortField: 'sortField',
	sortType: 'sortType',
	page: 'page',
	limit: 'limit',
	id: 'id',
	externalIdKpHD: 'externalId.kpHD',
	externalIdImdb: 'externalId.imdb',
	externalIdTmdb: 'externalId.tmdb',
	name: 'name',
	alternativeName: 'alternativeName',
	enName: 'enName',
	namesName: 'names.name',
	type: 'type',
	typeNumber: 'typeNumber',
	year: 'year',
	description: 'description',
	shortDescription: 'shortDescription',
	slogan: 'slogan',
	status: 'status',
	ratingKp: 'rating.kp',
	ratingImdb: 'rating.imdb',
	ratingTmdb: 'rating.tmdb',
	ratingFilmCritics: 'rating.filmCritics',
	ratingRussianFilmCritics: 'rating.russianFilmCritics',
	ratingAwait: 'rating.await',
	votesKp: 'votes.kp',
	votesImdb: 'votes.imdb',
	votesTmdb: 'votes.tmdb',
	votesFilmCritics: 'votes.filmCritics',
	votesRussianFilmCritics: 'votes.russianFilmCritics',
	votesAwait: 'votes.await',
	movieLength: 'movieLength',
	ratingMpaa: 'ratingMpaa',
	ageRating: 'ageRating',
	logoUrl: 'logo.url',
	posterUrl: 'poster.url',
	posterPreviewUrl: 'poster.previewUrl',
	backdropUrl: 'backdrop.url',
	backdropPreviewUrl: 'backdrop.previewUrl',
	videosTrailersUrl: 'videos.trailers.url',
	videosTrailersName: 'videos.trailers.name',
	videosTrailersSite: 'videos.trailers.site',
	videosTrailersType: 'videos.trailers.type',
	genresName: 'genres,name',
	countriesName: 'countries.name',
	personsId: 'persons.id',
	personsPhoto: 'persons.photo',
	personsName: 'persons.name',
	personsEnName: 'persons.enName',
	reviewInfoCount: 'reviewInfo.count',
	reviewInfoPositiveCount: 'reviewInfo.positiveCount',
	reviewInfoPercentage: 'reviewInfo.percentage',
	seasonsInfoNumber: 'seasonsInfo.number',
	seasonsInfoEpisodesCount: 'seasonsInfo.episodesCount',
	budgetValue: 'budget.value',
	budgetCurrency: 'budget.currency',
	feesWorldValue: 'fees.world.value',
	feesWorldCurrency: 'fees.world.currency',
	feesRussiaValue: 'fees.russia.value',
	feesRussiaCurrency: 'fees.russia.currency',
	feesUsaValue: 'fees.usa.value',
	feesUsaCurrency: 'fees.usa.currency',
	premiereCountry: 'premiere.country',
	premiereWorld: 'premiere.world',
	premiereRussia: 'premiere.russia',
	premiereDigital: 'premiere.digital',
	premiereCinema: 'premiere.cinema',
	similarMoviesId: 'similarMovies.id',
	sequelsAndPrequelsId: 'sequelsAndPrequels.id',
	watchabilityItemsName: 'watchability.items.name',
	releaseYearsStart: 'releaseYears.start',
	releaseYearsEnd: 'releaseYears.end',
	top10: 'top10',
	top250: 'top250',
	ticketsOnSale: 'ticketsOnSale',
	totalSeriesLength: 'totalSeriesLength',
	seriesLength: 'seriesLength',
	isSeries: 'isSeries',
	audienceCount: 'audience.count',
	audienceCountry: 'audience.country',
}
